;;; -*- mode: lisp; package: user -*-
;;;
;;; File: popup-dododo/editor.l
;;;
;;; License:
;;;
;;;   Copyright (c) 2007 MIYAMUKO Katsuyuki.
;;;
;;;   popup-dododo is released under an MIT license.
;;;   See popup-dododo/docs/MIT-LICENSE for full license.
;;;

(in-package :user)

(require "popup-dododo/editor/command")
(require "popup-dododo/editor/hooks")

(provide "popup-dododo/editor")

;;; End
